# Generated by Django 2.1 on 2018-08-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=100)),
                ('site_admin', models.BooleanField()),
                ('name', models.CharField(max_length=512)),
                ('node_id', models.CharField(max_length=512)),
                ('avatar_url', models.CharField(max_length=512)),
                ('gravatar_id', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=512)),
                ('html_url', models.CharField(max_length=512)),
                ('followers_url', models.CharField(max_length=512)),
                ('following_url', models.CharField(max_length=512)),
                ('gists_url', models.CharField(max_length=512)),
                ('starred_url', models.CharField(max_length=512)),
                ('subscriptions_url', models.CharField(max_length=512)),
                ('organizations_url', models.CharField(max_length=512)),
                ('repos_url', models.CharField(max_length=512)),
                ('events_url', models.CharField(max_length=512)),
                ('received_events_url', models.CharField(max_length=512)),
                ('company', models.CharField(max_length=512)),
                ('blog', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=512)),
                ('hireable', models.BooleanField()),
                ('bio', models.TextField()),
                ('public_repos', models.IntegerField()),
                ('public_gists', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
